name: Auto PR Change Log

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate change log
        run: |
          echo "🔄 Generating change log..."
          CHANGES=$(git diff --name-only origin/main)
          echo "Detected changes:"
          echo "$CHANGES"

      - name: Update PR description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const changelog = `\n${process.env.CHANGES}\n`;
            const pr = context.payload.pull_request;
            const body = pr.body.replace(
              /<!-- AUTO_CHANGELOG_START -->[\s\S]*<!-- AUTO_CHANGELOG_END -->/,
              `<!-- AUTO_CHANGELOG_START -->\n${changelog}<!-- AUTO_CHANGELOG_END -->`
            );
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              body: body
            });